# Generated by Django 5.1.5 on 2026-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('DAY_PUBLISHED', 'Journée publiée'), ('NEW_ACTIVITY', 'Nouvelle activité'), ('COMPLAINT_CREATED', 'Nouvelle réclamation'), ('COMPLAINT_UPDATED', 'Réclamation mise à jour'), ('COMPLAINT_REPLY', 'Réponse à une réclamation')], max_length=30),
        ),
    ]
