# Generated by Django 5.1.5 on 2026-09-04 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGED', 'Mot de passe modifié'), ('CODE_ISSUED', "Code d'accès généré"), ('CODE_REVOKED', "Code d'accès révoqué"), ('CODE_CLAIMED', "Code d'accès utilisé"), ('CODE_CLAIM_FAILED', "Échec d'utilisation d'un code"), ('CHILD_CREATED', 'Enfant créé'), ('CHILD_UPDATED', 'Enfant modifié'), ('CHILD_ARCHIVED', 'Enfant archivé'), ('CHILD_RESTORED', 'Enfant restauré'), ('CHILD_DELETED', 'Enfant supprimé'), ('GUARDIAN_LINKED', 'Parent rattaché'), ('GUARDIAN_REVOKED', 'Rattachement révoqué'), ('COMPLAINT_STATUS_CHANGED', 'Statut de réclamation modifié')], max_length=50)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='children.child')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Entrées d'audit",
                'db_table': 'audit_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', '-created_at'], name='audit_audit_child_i_fc2a16_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx')],
            },
        ),
    ]
