# Generated by Django 5.1.5 on 2026-09-04 09:36

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('PARENT', 'Parent'), ('STAFF', 'Personnel'), ('ADMIN', 'Administrateur')], default='PARENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildAccessCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_lookup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_hint', models.CharField(blank=True, max_length=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Code d'accès enfant",
                'verbose_name_plural': "Codes d'accès enfant",
                'db_table': 'accounts_childaccesscode',
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('MOTHER', 'Mère'), ('FATHER', 'Père'), ('GUARDIAN', 'Tuteur'), ('OTHER', 'Autre')], default='GUARDIAN', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lien de garde',
                'verbose_name_plural': 'Liens de garde',
                'db_table': 'accounts_guardianship',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(blank=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(default='fr', max_length=5)),
            ],
            options={
                'verbose_name': 'Profil parent',
                'verbose_name_plural': 'Profils parents',
                'db_table': 'accounts_parentprofile',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('job_title', models.CharField(blank=True, max_length=80)),
                ('assigned_age_group', models.CharField(blank=True, max_length=20)),
                ('hired_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Profil personnel',
                'verbose_name_plural': 'Profils personnel',
                'db_table': 'accounts_staffprofile',
            },
        ),
    ]
