# Generated by Django 5.1.5 on 2026-09-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childaccesscode',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='children.child'),
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='children.child'),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='accounts.parentprofile'),
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_codes', to='accounts.parentprofile'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianship',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['parent'], name='idx_guardianship_active_parent'),
        ),
        migrations.AddIndex(
            model_name='guardianship',
            index=models.Index(condition=models.Q(('revoked_at__isnull', True)), fields=['child'], name='idx_guardianship_active_child'),
        ),
        migrations.AddConstraint(
            model_name='guardianship',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='uniq_guardianship_parent_child'),
        ),
        migrations.AddConstraint(
            model_name='guardianship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('revoked_at__isnull', True)), fields=('child',), name='uniq_primary_guardian_per_child'),
        ),
        migrations.AddConstraint(
            model_name='childaccesscode',
            constraint=models.UniqueConstraint(condition=models.Q(('claimed_at__isnull', True), ('revoked_at__isnull', True)), fields=('child',), name='uniq_live_access_code_per_child'),
        ),
    ]
