# Generated by Django 5.1.5 on 2026-09-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='can_send_messages',
        ),
    ]
