# Generated by Django 5.1.5 on 2026-09-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_parentprofile_can_send_messages'),
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childaccesscode',
            options={'verbose_name': "Code d'accès parent", 'verbose_name_plural': "Codes d'accès parent"},
        ),
        migrations.RemoveConstraint(
            model_name='childaccesscode',
            name='uniq_live_access_code_per_child',
        ),
        migrations.RemoveField(
            model_name='childaccesscode',
            name='claimed_at',
        ),
        migrations.RemoveField(
            model_name='childaccesscode',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='childaccesscode',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childaccesscode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='accounts.parentprofile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='childaccesscode',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('child', 'parent'), name='uniq_live_access_code_per_guardian'),
        ),
    ]
