# Generated by Django 5.1.5 on 2026-09-04 09:36

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField(db_index=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Garçon'), ('F', 'Fille'), ('OTHER', 'Autre')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='children/photos/')),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('WAITLIST', "Liste d'attente")], default='ACTIVE', max_length=12)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'db_table': 'children_child',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='children_ch_last_na_7fe854_idx'), models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['status'], name='idx_child_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_of_birth__lte', django.db.models.functions.datetime.Now())), name='child_dob_not_in_future'), models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', False), ('status', 'ARCHIVED')), models.Q(models.Q(('status', 'ARCHIVED'), _negated=True), ('archived_at__isnull', True)), _connector='OR'), name='child_archived_status_consistent')],
            },
        ),
    ]
