# Generated by Django 5.1.5 on 2026-09-04 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ART', 'Arts plastiques'), ('MUSIC', 'Musique'), ('OUTDOOR', 'Jeux extérieurs'), ('STORY', 'Lecture'), ('MOTOR', 'Motricité'), ('EDUCATIONAL', 'Éveil éducatif'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activities_activity',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_participations', to='children.child')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'db_table': 'activities_activityparticipation',
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='activities/photos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='activities/thumbnails/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Photo d'activité",
                'verbose_name_plural': "Photos d'activité",
                'db_table': 'activities_activityphoto',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-date'], name='activities__date_cd0fed_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__isnull', True), ('start_time__isnull', True), ('end_time__gte', models.F('start_time')), _connector='OR'), name='activity_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='activityparticipation',
            index=models.Index(fields=['child', 'activity'], name='activities__child_i_c3d584_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipation',
            constraint=models.UniqueConstraint(fields=('activity', 'child'), name='uniq_activity_participation'),
        ),
    ]
