# Generated by Django 5.1.5 on 2026-09-04 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('general_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié')], default='DRAFT', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journée',
                'verbose_name_plural': 'Journées',
                'db_table': 'care_dailyrecord',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('MEAL', 'Repas'), ('BOTTLE', 'Biberon'), ('SLEEP', 'Sommeil'), ('DIAPER', 'Change'), ('TOILET', 'Toilettes'), ('TEMPERATURE', 'Température'), ('MOOD', 'Humeur'), ('NOTE', 'Note'), ('ACTIVITY', 'Activité'), ('MESSAGE', 'Message')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('local_date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='activities.activity')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'db_table': 'care_timelineevent',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
    ]
