# Generated by Django 5.1.5 on 2026-09-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('care', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='dailyrecord',
            index=models.Index(fields=['child', '-date'], name='care_dailyr_child_i_73b4ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('child', 'date'), name='uniq_daily_record_per_child_day'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['child', 'local_date', 'occurred_at'], name='idx_timeline_child_day'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['child', '-occurred_at'], name='idx_timeline_child_recent'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['child', 'type', 'local_date'], name='idx_timeline_child_type'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('occurred_at')), _connector='OR'), name='timeline_event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'ACTIVITY'), _negated=True), ('activity__isnull', False), _connector='OR'), name='timeline_activity_reference_required'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'MESSAGE'), _negated=True), ('message__isnull', False), _connector='OR'), name='timeline_message_reference_required'),
        ),
        migrations.AddConstraint(
            model_name='timelineevent',
            constraint=models.UniqueConstraint(condition=models.Q(('activity__isnull', False)), fields=('activity', 'child'), name='uniq_activity_event_per_child'),
        ),
    ]
