# Generated by Django 5.1.5 on 2026-09-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='type',
            field=models.CharField(choices=[('MEAL', 'Repas'), ('BOTTLE', 'Biberon'), ('SLEEP', 'Sommeil'), ('DIAPER', 'Change'), ('TOILET', 'Toilettes'), ('TEMPERATURE', 'Température'), ('MOOD', 'Humeur'), ('NOTE', 'Note'), ('ACTIVITY', 'Activité')], max_length=20),
        ),
    ]
